from selenium import webdriver

browser = webdriver.Chrome('C:\\Users\Tobi\Downloads\chromedriver_win32/chromedriver')
browser.get('http://35.197.243.154:5000/')

################## users #################################
elem = browser.find_element_by_link_text('Register')
elem.click()
firstname = browser.find_element_by_id('first_name')
firstname.send_keys('frank')
lastname = browser.find_element_by_id('last_name')
lastname.send_keys('frank')
email = browser.find_element_by_id('email')
email.send_keys('frank@frank.com')
submit = browser.find_element_by_id('submit')
submit.click()

elem = browser.find_element_by_link_text('Register')
elem.click()
firstname = browser.find_element_by_id('first_name')
firstname.send_keys('geff')
lastname = browser.find_element_by_id('last_name')
lastname.send_keys('geff')
email = browser.find_element_by_id('email')
email.send_keys('geff@geff.com')
submit = browser.find_element_by_id('submit')
submit.click()

elem = browser.find_element_by_link_text('Register')
elem.click()
firstname = browser.find_element_by_id('first_name')
firstname.send_keys('hannah')
lastname = browser.find_element_by_id('last_name')
lastname.send_keys('hannah')
email = browser.find_element_by_id('email')
email.send_keys('hannah@hannah.com')
submit = browser.find_element_by_id('submit')
submit.click()

elem = browser.find_element_by_link_text('Register')
elem.click()
firstname = browser.find_element_by_id('first_name')
firstname.send_keys('tj')
lastname = browser.find_element_by_id('last_name')
lastname.send_keys('tj')
email = browser.find_element_by_id('email')
email.send_keys('tj@tj.com')
submit = browser.find_element_by_id('submit')
submit.click()

########################### tanks ##########################################
login = browser.find_element_by_link_text('Login')
login.click()
email = browser.find_element_by_id('email')
email.send_keys('geff@geff.com')
submit = browser.find_element_by_id('submit')
submit.click()

tanks = browser.find_element_by_link_text('Tanks')
tanks.click()
name = browser.find_element_by_id('name')
name.send_keys('Fish1')
description = browser.find_element_by_id('description')
description.send_keys('Fish')
ammonia = browser.find_element_by_id('ammonia')
ammonia.send_keys('3')
nitrate = browser.find_element_by_id('nitrate')
nitrate.send_keys('1.5')
nitrite = browser.find_element_by_id('nitrite')
nitrite.send_keys('0')
submit = browser.find_element_by_id('submit')
submit.click()

logout = browser.find_element_by_link_text('Logout')
logout.click()

###################################################################################
login = browser.find_element_by_link_text('Login')
login.click()
email = browser.find_element_by_id('email')
email.send_keys('frank@frank.com')
submit = browser.find_element_by_id('submit')
submit.click()

tanks = browser.find_element_by_link_text('Tanks')
tanks.click()
name = browser.find_element_by_id('name')
name.send_keys('Fish20')
ammonia = browser.find_element_by_id('ammonia')
ammonia.send_keys('10')
nitrate = browser.find_element_by_id('nitrate')
nitrate.send_keys('3.5')
nitrite = browser.find_element_by_id('nitrite')
nitrite.send_keys('2')
submit = browser.find_element_by_id('submit')
submit.click()

tanks = browser.find_element_by_link_text('Tanks')
tanks.click()
name = browser.find_element_by_id('name')
name.send_keys('Fish2')
description = browser.find_element_by_id('description')
description.send_keys('Fishes')
ammonia = browser.find_element_by_id('ammonia')
ammonia.send_keys('3')
nitrate = browser.find_element_by_id('nitrate')
nitrate.send_keys('1.5')
nitrite = browser.find_element_by_id('nitrite')
nitrite.send_keys('0')
submit = browser.find_element_by_id('submit')
submit.click()

logout = browser.find_element_by_link_text('Logout')
logout.click()

###########################################################################
login = browser.find_element_by_link_text('Login')
login.click()
email = browser.find_element_by_id('email')
email.send_keys('geff@geff.com')
submit = browser.find_element_by_id('submit')
submit.click()

tanks = browser.find_element_by_link_text('Tanks')
tanks.click()
name = browser.find_element_by_id('name')
name.send_keys('Fish1')
description = browser.find_element_by_id('description')
description.send_keys('Fish')
ammonia = browser.find_element_by_id('ammonia')
ammonia.send_keys('2')
nitrate = browser.find_element_by_id('nitrate')
nitrate.send_keys('0.5')
nitrite = browser.find_element_by_id('nitrite')
nitrite.send_keys('3')
submit = browser.find_element_by_id('submit')
submit.click()

logout = browser.find_element_by_link_text('Logout')
logout.click()

#################################################################
login = browser.find_element_by_link_text('Login')
login.click()
email = browser.find_element_by_id('email')
email.send_keys('tj@tj.com')
submit = browser.find_element_by_id('submit')
submit.click()

tanks = browser.find_element_by_link_text('Tanks')
tanks.click()
name = browser.find_element_by_id('name')
name.send_keys('Fish19')
ammonia = browser.find_element_by_id('ammonia')
ammonia.send_keys('10')
nitrate = browser.find_element_by_id('nitrate')
nitrate.send_keys('3.5')
nitrite = browser.find_element_by_id('nitrite')
nitrite.send_keys('2')
submit = browser.find_element_by_id('submit')
submit.click()

tanks = browser.find_element_by_link_text('Tanks')
tanks.click()
name = browser.find_element_by_id('name')
name.send_keys('Fish2')
description = browser.find_element_by_id('description')
description.send_keys('Fishes')
ammonia = browser.find_element_by_id('ammonia')
ammonia.send_keys('3')
nitrate = browser.find_element_by_id('nitrate')
nitrate.send_keys('4.5')
nitrite = browser.find_element_by_id('nitrite')
nitrite.send_keys('0')
submit = browser.find_element_by_id('submit')
submit.click()

logout = browser.find_element_by_link_text('Logout')
logout.click()

########################################################
login = browser.find_element_by_link_text('Login')
login.click()
email = browser.find_element_by_id('email')
email.send_keys('hannah@hannah.com')
submit = browser.find_element_by_id('submit')
submit.click()

tanks = browser.find_element_by_link_text('Tanks')
tanks.click()
name = browser.find_element_by_id('name')
name.send_keys('Fish1')
description = browser.find_element_by_id('description')
description.send_keys('Fish')
ammonia = browser.find_element_by_id('ammonia')
ammonia.send_keys('3')
nitrate = browser.find_element_by_id('nitrate')
nitrate.send_keys('1.5')
nitrite = browser.find_element_by_id('nitrite')
nitrite.send_keys('0')
submit = browser.find_element_by_id('submit')
submit.click()

logout = browser.find_element_by_link_text('Logout')
logout.click()
###########################################################################
login = browser.find_element_by_link_text('Login')
login.click()
email = browser.find_element_by_id('email')
email.send_keys('tj@tj.com')
submit = browser.find_element_by_id('submit')
submit.click()

tanks = browser.find_element_by_link_text('Tanks')
tanks.click()
name = browser.find_element_by_id('name')
name.send_keys('Fish19')
ammonia = browser.find_element_by_id('ammonia')
ammonia.send_keys('10')
nitrate = browser.find_element_by_id('nitrate')
nitrate.send_keys('3.5')
nitrite = browser.find_element_by_id('nitrite')
nitrite.send_keys('2')
submit = browser.find_element_by_id('submit')
submit.click()

tanks = browser.find_element_by_link_text('Tanks')
tanks.click()
name = browser.find_element_by_id('name')
name.send_keys('Fish234')
description = browser.find_element_by_id('description')
description.send_keys('Fishes')
ammonia = browser.find_element_by_id('ammonia')
ammonia.send_keys('3')
nitrate = browser.find_element_by_id('nitrate')
nitrate.send_keys('4.5')
nitrite = browser.find_element_by_id('nitrite')
nitrite.send_keys('0')
submit = browser.find_element_by_id('submit')
submit.click()

logout = browser.find_element_by_link_text('Logout')
logout.click()